WIKIPEDIARECORDS= LOAD 's3://' USING PigStorage(' ') AS (site:chararray, page:chararray, views:int, totalbytes:int);
GROUPWIKIPEDIARECORDS= GROUP WIKIPEDIARECORDS BY  page;
SUM = FOREACH  GROUPWIKIPEDIARECORDS GENERATE group, SUM(WIKIPEDIARECORDS.views) AS soma;
ORDEREDSUM =  ORDER sum BY soma DESC;
TOP10 = LIMIT ORDEREDSUM 10;
STORE TOP10 INTO 'myoutputex1' USING PigStorage ('\t') ;

